import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';

function capture(command,args){return new Promise((resolve,reject)=>{const proc=spawn(command,args);let output='',errors='';proc.stdout.on('data',chunk=>{output+=chunk;});proc.stderr.on('data',chunk=>{errors+=chunk;});proc.on('close',code=>code===0?resolve(output):reject(new Error(errors.trim()||`${command}: код ${code}`)));proc.on('error',reject);});}

export function recognitionCandidates(lookup,trackDuration,fingerprintDuration){
  const candidates=[];
  for(const result of lookup?.results||[])for(const recording of result.recordings||[]){
    const artist=(recording.artists||[]).map(item=>item.name).filter(Boolean).join(', '),title=String(recording.title||'').trim();if(!artist||!title)continue;
    const difference=recording.duration==null?999:Math.abs(Number(recording.duration)-Number(trackDuration||fingerprintDuration));
    const groups=(recording.releasegroups||[]).filter(group=>{const secondary=(group.secondarytypes||[]).map(value=>String(value).toLowerCase());return !secondary.some(value=>['compilation','dj-mix','remix','live'].includes(value))&&!(group.artists||[]).some(item=>item.name==='Various Artists');}).map(group=>{const years=(group.releases||[]).map(release=>Number(release.date?.year)).filter(Number.isFinite);return{album:group.title||'',year:years.length?Math.min(...years):null,release_group_id:group.id,type:String(group.type||'').toLowerCase()};}).sort((a,b)=>({album:0,ep:1,single:2}[a.type]??3)-({album:0,ep:1,single:2}[b.type]??3)||(a.year||9999)-(b.year||9999));
    const release=groups[0]||{},confidence=Math.min(1,Number(result.score||0)*(difference<=3?1:difference<=10?.9:difference<=20?.7:.45)*(release.release_group_id?1.01:1));
    if(!candidates.some(item=>item.artist===artist&&item.title===title))candidates.push({artist,title,album:release.album||'',year:release.year||null,release_group_id:release.release_group_id||null,duration_seconds:recording.duration??null,confidence,recording_id:recording.id});
  }
  return candidates.sort((a,b)=>b.confidence-a.confidence).slice(0,5);
}

export function createRecognitionService({db,storageDir,uploadDir,extractCover,defaultEnabled=false,defaultClientKey='',fetchImpl=fetch,execute=capture,logError=console.error}){
  const root=path.resolve(storageDir);let busy=false;
  const sourcePath=key=>{if(!key)return null;const file=path.resolve(root,key);return file.startsWith(`${root}${path.sep}`)&&fs.existsSync(file)&&fs.statSync(file).isFile()?file:null;};
  async function settings(){const rows=await db.prepare("SELECT key,value FROM app_settings WHERE key IN ('recognition_enabled','acoustid_client_key')").all(),values=Object.fromEntries(rows.map(row=>[row.key,row.value]));return{enabled:values.recognition_enabled===undefined?defaultEnabled:values.recognition_enabled==='true',clientKey:values.acoustid_client_key===undefined?defaultClientKey:values.acoustid_client_key};}
  async function saveSettings({enabled,keyProvided,clientKey}){await db.transaction(async tx=>{await tx.prepare(`INSERT INTO app_settings(key,value,updated_at) VALUES('recognition_enabled',?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).run(enabled?'true':'false');if(keyProvided)await tx.prepare(`INSERT INTO app_settings(key,value,updated_at) VALUES('acoustid_client_key',?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).run(clientKey);});return settings();}
  async function addCover(trackId,releaseGroupId){const track=await db.prepare('SELECT cover_key FROM tracks WHERE id=?').get(trackId);if(!track||track.cover_key)return;const response=await fetchImpl(`https://coverartarchive.org/release-group/${encodeURIComponent(releaseGroupId)}/front-500`,{headers:{'User-Agent':'FamilyMusic/1.0'},signal:AbortSignal.timeout(30000)});if(!response.ok)return;const bytes=Buffer.from(await response.arrayBuffer());if(!bytes.length||bytes.length>12*1024*1024)return;const temporary=path.join(uploadDir,`cover-${crypto.randomUUID()}.image`);fs.writeFileSync(temporary,bytes,{mode:0o640});try{const coverKey=await extractCover(temporary,trackId);if(coverKey)await db.prepare('UPDATE tracks SET cover_key=?,cover_checked=1 WHERE id=? AND cover_key IS NULL').run(coverKey,trackId);}finally{fs.rmSync(temporary,{force:true});}}
  async function processNext(){if(busy)return false;const configured=await settings();if(!configured.enabled||!configured.clientKey)return false;busy=true;let job;try{const claimed=await db.prepare(`UPDATE recognition_jobs SET status='processing',attempts=attempts+1,updated_at=CURRENT_TIMESTAMP WHERE id=(SELECT id FROM recognition_jobs WHERE status IN ('queued','retry') AND available_at<=CURRENT_TIMESTAMP ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING *`).run();job=claimed.rows[0];if(!job)return false;const track=await db.prepare('SELECT * FROM tracks WHERE id=?').get(job.track_id),source=sourcePath(track?.storage_key);if(!source)throw new Error('Исходный файл не найден');const fingerprint=JSON.parse(await execute('fpcalc',['-json',source]));const body=new URLSearchParams({client:configured.clientKey,duration:String(Math.round(fingerprint.duration)),fingerprint:fingerprint.fingerprint,meta:'recordings releases releasegroups'});const response=await fetchImpl('https://api.acoustid.org/v2/lookup',{method:'POST',body,signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`AcoustID: HTTP ${response.status}`);const lookup=await response.json();if(lookup.status!=='ok')throw new Error(`AcoustID: ${lookup.error?.message||'ошибка'}`);const candidates=recognitionCandidates(lookup,track.duration_seconds,fingerprint.duration),best=candidates[0];if(!best)await db.prepare("UPDATE recognition_jobs SET status='unmatched',candidates_json='[]',error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(job.id);else if(best.confidence>=.8)await db.transaction(async tx=>{await tx.prepare("UPDATE tracks SET title=?,artist=?,album=CASE WHEN album='' THEN ? ELSE album END,year=COALESCE(year,?) WHERE id=?").run(best.title,best.artist,best.album||'',best.year,job.track_id);await tx.prepare("UPDATE recognition_jobs SET status='applied',confidence=?,suggested_title=?,suggested_artist=?,candidates_json=?,error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(best.confidence,best.title,best.artist,JSON.stringify(candidates),job.id);});else await db.prepare("UPDATE recognition_jobs SET status='review',confidence=?,suggested_title=?,suggested_artist=?,candidates_json=?,error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(best.confidence,best.title,best.artist,JSON.stringify(candidates),job.id);if(best&&best.confidence>=.8&&best.release_group_id)await addCover(job.track_id,best.release_group_id).catch(error=>logError('Не удалось загрузить обложку:',error.message));return true;}catch(error){const message=String(error.message||error).slice(0,1000),attempts=Number(job?.attempts||0);if(job)await db.prepare(`UPDATE recognition_jobs SET status=?,available_at=CURRENT_TIMESTAMP + (? * INTERVAL '1 second'),error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(attempts>=5?'failed':'retry',Math.min(3600,30*(2**Math.max(0,attempts-1))),message,job.id).catch(()=>{});logError('Ошибка распознавания:',message);return false;}finally{busy=false;}}
  async function recover(){await db.prepare("UPDATE recognition_jobs SET status='retry',available_at=CURRENT_TIMESTAMP WHERE status='processing'").run();return processNext();}
  return{settings,saveSettings,addCover,processNext,recover};
}
